### ISSUE TITLE
Refactor DeckAPIView to use Viewset

### ISSUE THREAD

**Issue by cacoze** [yamawakimiho/memo#1]
https://github.com/yamawakimiho/memo/blob/5fe7b42cda8cea12790373a9faa97d7bed163b69/memo/views.py#L12-L46

Hi @yamawakimiho , this piece of code seems a good place for you to refactor and use DRF Viewsets. When you're mainly creating a CRUD API, the `ModelViewSet` might cover most of the scenarios. ([Here's a good documentation page about viewsets](https://www.django-rest-framework.org/api-guide/viewsets/))

Also, for passing the request to the serializer, you might want to check the Viewset method `get_serializer_context()`

**Comment by yamawakimiho** [comment]
Hello @cacoze, I've refactored the DecksAPIView to use ModelViewSet as suggested, however, it's not requesting the context object to the serializer as it did before (it has stopped to return 500 and error in the serializer) so I'm just overwriting the perform_create() instead of create() in the DecksAPIView.
